/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class CustomerLogin extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLogin
     */
    public CustomerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NAME_jLabel1 = new javax.swing.JLabel();
        NAME_jTextField1 = new javax.swing.JTextField();
        PASSWORD_jLabel2 = new javax.swing.JLabel();
        PASSWORD_jTextField2 = new javax.swing.JTextField();
        LOGIN_jToggleButton1 = new javax.swing.JToggleButton();
        SIGNUP_jToggleButton2 = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        getContentPane().setLayout(null);

        NAME_jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NAME_jLabel1.setText("     NAME");
        getContentPane().add(NAME_jLabel1);
        NAME_jLabel1.setBounds(109, 43, 72, 28);

        NAME_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME_jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(NAME_jTextField1);
        NAME_jTextField1.setBounds(199, 43, 118, 28);

        PASSWORD_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PASSWORD_jLabel2.setText("PASSWORD");
        getContentPane().add(PASSWORD_jLabel2);
        PASSWORD_jLabel2.setBounds(103, 97, 78, 30);
        getContentPane().add(PASSWORD_jTextField2);
        PASSWORD_jTextField2.setBounds(199, 97, 118, 30);

        LOGIN_jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LOGIN_jToggleButton1.setText("LOGIN");
        getContentPane().add(LOGIN_jToggleButton1);
        LOGIN_jToggleButton1.setBounds(143, 158, 105, 31);

        SIGNUP_jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SIGNUP_jToggleButton2.setText("SIGN UP");
        getContentPane().add(SIGNUP_jToggleButton2);
        SIGNUP_jToggleButton2.setBounds(285, 243, 105, 33);

        pack();
    }// </editor-fold>                        

    private void NAME_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton LOGIN_jToggleButton1;
    private javax.swing.JLabel NAME_jLabel1;
    private javax.swing.JTextField NAME_jTextField1;
    private javax.swing.JLabel PASSWORD_jLabel2;
    private javax.swing.JTextField PASSWORD_jTextField2;
    private javax.swing.JToggleButton SIGNUP_jToggleButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
