/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
package rapid_rentals;
public class CustomerShow_BookCar extends javax.swing.JFrame {

    /**
     * Creates new form CustomerShow_BookCar
     */
    public CustomerShow_BookCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGOUT_BTTN = new javax.swing.JToggleButton();
        SHOWCARS_BTTN = new javax.swing.JToggleButton();
        NEWBOOKING_BTTN = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        setPreferredSize(new java.awt.Dimension(428, 350));
        getContentPane().setLayout(null);

        LOGOUT_BTTN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LOGOUT_BTTN.setText("LOG OUT");
        LOGOUT_BTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT_BTTNActionPerformed(evt);
            }
        });
        getContentPane().add(LOGOUT_BTTN);
        LOGOUT_BTTN.setBounds(283, 245, 104, 32);

        SHOWCARS_BTTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SHOWCARS_BTTN.setText("SHOW CARS");
        SHOWCARS_BTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWCARS_BTTNActionPerformed(evt);
            }
        });
        getContentPane().add(SHOWCARS_BTTN);
        SHOWCARS_BTTN.setBounds(140, 50, 130, 40);

        NEWBOOKING_BTTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NEWBOOKING_BTTN.setText("NEW BOOKING");
        NEWBOOKING_BTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEWBOOKING_BTTNActionPerformed(evt);
            }
        });
        getContentPane().add(NEWBOOKING_BTTN);
        NEWBOOKING_BTTN.setBounds(140, 120, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SHOWCARS_BTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWCARS_BTTNActionPerformed
        // TODO add your handling code here:
     CustomerShow o=new CustomerShow();
     this.setVisible(false);
     o.setVisible(true);
    }//GEN-LAST:event_SHOWCARS_BTTNActionPerformed

    private void NEWBOOKING_BTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEWBOOKING_BTTNActionPerformed
        // TODO add your handling code here:
        CustomerNewBooking ob=new CustomerNewBooking();
        this.setVisible(false);
        ob.setVisible(true);
    }//GEN-LAST:event_NEWBOOKING_BTTNActionPerformed

    private void LOGOUT_BTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUT_BTTNActionPerformed
        // TODO add your handling code here:
        Customer_Login p=new Customer_Login();
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_LOGOUT_BTTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerShow_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerShow_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerShow_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerShow_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerShow_BookCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton LOGOUT_BTTN;
    private javax.swing.JToggleButton NEWBOOKING_BTTN;
    private javax.swing.JToggleButton SHOWCARS_BTTN;
    // End of variables declaration//GEN-END:variables
}
