/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapid.rentals;

/**
 *
 * @author GAURAV
 */
public class front extends javax.swing.JFrame {

    /**
     * Creates new form front
     */
    public front() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        customer = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        rapid_rentals = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        setPreferredSize(new java.awt.Dimension(650, 400));
        getContentPane().setLayout(null);

        customer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customer.setText("CUSTOMER");
        getContentPane().add(customer);
        customer.setBounds(490, 90, 113, 25);

        admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin.setText("ADMIN");
        getContentPane().add(admin);
        admin.setBounds(493, 50, 110, 25);

        welcome.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome to");
        getContentPane().add(welcome);
        welcome.setBounds(20, 40, 160, 30);

        rapid_rentals.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rapid_rentals.setForeground(new java.awt.Color(255, 255, 255));
        rapid_rentals.setText("RAPID RENTALS");
        getContentPane().add(rapid_rentals);
        rapid_rentals.setBounds(20, 60, 340, 60);

        photo.setIcon(new javax.swing.ImageIcon("C:\\Users\\GAURAV\\Downloads\\car_rent.png")); // NOI18N
        photo.setText("jLabel4");
        getContentPane().add(photo);
        photo.setBounds(0, 0, 640, 390);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton admin;
    private javax.swing.JButton customer;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel rapid_rentals;
    private javax.swing.JLabel welcome;
    // End of variables declaration                   
}
