package rapid.rentals;
import javax.swing.JOptionPane;
 import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;


public class CustomerLogin extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLogin
     */
   /**
   **/
    public CustomerLogin() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NAME_jLabel1 = new javax.swing.JLabel();
        NAME_TEXT = new javax.swing.JTextField();
        PASSWORD_jLabel2 = new javax.swing.JLabel();
        PASSWORD_TEXT = new javax.swing.JTextField();
        LOGIN_jToggleButton1 = new javax.swing.JToggleButton();
        SIGNUP_jToggleButton2 = new javax.swing.JToggleButton();
        valid = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        setPreferredSize(new java.awt.Dimension(428, 350));
        getContentPane().setLayout(null);

        NAME_jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NAME_jLabel1.setText("     NAME");
        getContentPane().add(NAME_jLabel1);
        NAME_jLabel1.setBounds(109, 43, 72, 28);

        NAME_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME_TEXTActionPerformed(evt);
            }
        });
        getContentPane().add(NAME_TEXT);
        NAME_TEXT.setBounds(199, 43, 118, 28);

        PASSWORD_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PASSWORD_jLabel2.setText("PASSWORD");
        getContentPane().add(PASSWORD_jLabel2);
        PASSWORD_jLabel2.setBounds(103, 97, 78, 30);
        getContentPane().add(PASSWORD_TEXT);
        PASSWORD_TEXT.setBounds(199, 97, 118, 30);

        LOGIN_jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LOGIN_jToggleButton1.setText("LOGIN");
        LOGIN_jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(LOGIN_jToggleButton1);
        LOGIN_jToggleButton1.setBounds(143, 158, 105, 31);

        SIGNUP_jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SIGNUP_jToggleButton2.setText("SIGN UP");
        getContentPane().add(SIGNUP_jToggleButton2);
        SIGNUP_jToggleButton2.setBounds(285, 243, 105, 33);
        getContentPane().add(valid);
        valid.setBounds(104, 210, 190, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAME_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME_TEXTActionPerformed

    private void LOGIN_jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_jToggleButton1ActionPerformed
        String pass1=PASSWORD_TEXT.getText();
         String name1 =NAME_TEXT.getText();
        
        try
        {
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/login",
                        "root", "01234");
            PreparedStatement st = (PreparedStatement) connection.prepareStatement("Select name, password from login_info where name=? and password=?");
                   st.setString(1,name1);
                   st.setString(2,pass1);
                  
            
           
            ResultSet rs=st.executeQuery();
            if(rs.next())
            {
                CustomerShow_BookCar obj=new CustomerShow_BookCar();
                obj.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Login Failed.Please Try Again");
                dispose();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_LOGIN_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton LOGIN_jToggleButton1;
    private javax.swing.JTextField NAME_TEXT;
    private javax.swing.JLabel NAME_jLabel1;
    private javax.swing.JTextField PASSWORD_TEXT;
    private javax.swing.JLabel PASSWORD_jLabel2;
    private javax.swing.JToggleButton SIGNUP_jToggleButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel valid;
    // End of variables declaration//GEN-END:variables
}
