/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class CustomerNewBooking extends javax.swing.JFrame {

    /**
     * Creates new form CustomerNewBooking
     */
    public CustomerNewBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BookingName_lbl = new javax.swing.JLabel();
        Bookingname_txt = new javax.swing.JTextField();
        StartDate_lbl = new javax.swing.JLabel();
        StartDate_txt = new javax.swing.JTextField();
        EndDate_lbl = new javax.swing.JLabel();
        EndDate_txt = new javax.swing.JTextField();
        CarName_lbl = new javax.swing.JLabel();
        CarName_txt = new javax.swing.JTextField();
        kmTravelled_lbl = new javax.swing.JLabel();
        kmTravelled_txt = new javax.swing.JTextField();
        EstimatedBill_lbl = new javax.swing.JLabel();
        Bill_txt = new javax.swing.JTextField();
        ShowBill_bttn = new javax.swing.JToggleButton();
        Done_bttn = new javax.swing.JToggleButton();
        GoBack_bttn = new javax.swing.JToggleButton();
        LogOut_bttn = new javax.swing.JToggleButton();
        Rate_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        getContentPane().setLayout(null);

        BookingName_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BookingName_lbl.setText("BOOKING NAME");
        getContentPane().add(BookingName_lbl);
        BookingName_lbl.setBounds(71, 0, 105, 28);
        getContentPane().add(Bookingname_txt);
        Bookingname_txt.setBounds(207, 0, 108, 28);

        StartDate_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        StartDate_lbl.setText("START DATE");
        getContentPane().add(StartDate_lbl);
        StartDate_lbl.setBounds(71, 39, 105, 27);
        getContentPane().add(StartDate_txt);
        StartDate_txt.setBounds(207, 39, 108, 27);

        EndDate_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EndDate_lbl.setText("END DATE");
        getContentPane().add(EndDate_lbl);
        EndDate_lbl.setBounds(71, 72, 105, 29);
        getContentPane().add(EndDate_txt);
        EndDate_txt.setBounds(207, 72, 108, 29);

        CarName_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CarName_lbl.setText("CAR NAME");
        getContentPane().add(CarName_lbl);
        CarName_lbl.setBounds(71, 112, 105, 28);

        CarName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarName_txtActionPerformed(evt);
            }
        });
        getContentPane().add(CarName_txt);
        CarName_txt.setBounds(207, 112, 108, 28);

        kmTravelled_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kmTravelled_lbl.setText("km  TRAVELLED ");
        getContentPane().add(kmTravelled_lbl);
        kmTravelled_lbl.setBounds(71, 146, 105, 23);

        kmTravelled_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmTravelled_txtActionPerformed(evt);
            }
        });
        getContentPane().add(kmTravelled_txt);
        kmTravelled_txt.setBounds(207, 146, 108, 28);

        EstimatedBill_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EstimatedBill_lbl.setText("ESTIMATED BILL");
        getContentPane().add(EstimatedBill_lbl);
        EstimatedBill_lbl.setBounds(18, 209, 105, 28);
        getContentPane().add(Bill_txt);
        Bill_txt.setBounds(141, 209, 105, 24);

        ShowBill_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ShowBill_bttn.setText("SHOW BILL");
        getContentPane().add(ShowBill_bttn);
        ShowBill_bttn.setBounds(276, 209, 99, 28);

        Done_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Done_bttn.setText("DONE");
        getContentPane().add(Done_bttn);
        Done_bttn.setBounds(141, 255, 105, 23);

        GoBack_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GoBack_bttn.setText("GO BACK");
        GoBack_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBack_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(GoBack_bttn);
        GoBack_bttn.setBounds(10, 289, 105, 23);

        LogOut_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LogOut_bttn.setText("LOG OUT");
        getContentPane().add(LogOut_bttn);
        LogOut_bttn.setBounds(285, 289, 105, 23);

        Rate_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Rate_lbl.setText("          Rate -15 Rupees per km");
        getContentPane().add(Rate_lbl);
        Rate_lbl.setBounds(88, 185, 312, 13);

        pack();
    }// </editor-fold>                        

    private void CarName_txtActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void kmTravelled_txtActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void GoBack_bttnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerNewBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Bill_txt;
    private javax.swing.JLabel BookingName_lbl;
    private javax.swing.JTextField Bookingname_txt;
    private javax.swing.JLabel CarName_lbl;
    private javax.swing.JTextField CarName_txt;
    private javax.swing.JToggleButton Done_bttn;
    private javax.swing.JLabel EndDate_lbl;
    private javax.swing.JTextField EndDate_txt;
    private javax.swing.JLabel EstimatedBill_lbl;
    private javax.swing.JToggleButton GoBack_bttn;
    private javax.swing.JToggleButton LogOut_bttn;
    private javax.swing.JLabel Rate_lbl;
    private javax.swing.JToggleButton ShowBill_bttn;
    private javax.swing.JLabel StartDate_lbl;
    private javax.swing.JTextField StartDate_txt;
    private javax.swing.JLabel kmTravelled_lbl;
    private javax.swing.JTextField kmTravelled_txt;
    // End of variables declaration                   
}
