/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
package rapid_rentals;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Customer_Signup extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Signup
     */
    public Customer_Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        NAME_LABEL = new javax.swing.JLabel();
        NAME_TXT = new javax.swing.JTextField();
        PASSWORD_LABEL = new javax.swing.JLabel();
        PASSWORD_TXT = new javax.swing.JTextField();
        SAVE_BTTN = new javax.swing.JToggleButton();
        GO_BACK_BTTN = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        setPreferredSize(new java.awt.Dimension(427, 350));
        getContentPane().setLayout(null);

        NAME_LABEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NAME_LABEL.setText("         NAME");
        getContentPane().add(NAME_LABEL);
        NAME_LABEL.setBounds(90, 60, 80, 50);

        NAME_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME_TXTActionPerformed(evt);
            }
        });
        getContentPane().add(NAME_TXT);
        NAME_TXT.setBounds(180, 70, 120, 30);

        PASSWORD_LABEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PASSWORD_LABEL.setText("PASSWORD");
        getContentPane().add(PASSWORD_LABEL);
        PASSWORD_LABEL.setBounds(90, 120, 70, 40);

        PASSWORD_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORD_TXTActionPerformed(evt);
            }
        });
        getContentPane().add(PASSWORD_TXT);
        PASSWORD_TXT.setBounds(180, 120, 120, 30);

        SAVE_BTTN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SAVE_BTTN.setText("SAVE");
        SAVE_BTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVE_BTTNActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE_BTTN);
        SAVE_BTTN.setBounds(133, 179, 100, 30);

        GO_BACK_BTTN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GO_BACK_BTTN.setText("GO BACK");
        GO_BACK_BTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GO_BACK_BTTNActionPerformed(evt);
            }
        });
        getContentPane().add(GO_BACK_BTTN);
        GO_BACK_BTTN.setBounds(10, 253, 100, 30);

        pack();
    }// </editor-fold>                        

    private void PASSWORD_TXTActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void NAME_TXTActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void SAVE_BTTNActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String pass1=PASSWORD_TXT.getText();
        String name1=NAME_TXT.getText();
        try {
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","01234");
            PreparedStatement pst=(PreparedStatement)con.prepareStatement("INSERT INTO login_info name,password VALUES ?, ?");
            pst.setString(1,name1);
            pst.setString(2,pass1);
            //ResultSet rs=
                    pst.executeUpdate();
            //if(rs.next())
            //{
             JOptionPane.showMessageDialog(null,"Account Created");
             //dispose();
            //}
            //else
            //{
              //  JOptionPane.showMessageDialog(null,"Sorry Account Cannot be created");
                //dispose();
            //}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }                                         

    private void GO_BACK_BTTNActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        Customer_Login o=new Customer_Login();
        o.setVisible(true);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton GO_BACK_BTTN;
    private javax.swing.JLabel NAME_LABEL;
    private javax.swing.JTextField NAME_TXT;
    private javax.swing.JLabel PASSWORD_LABEL;
    private javax.swing.JTextField PASSWORD_TXT;
    private javax.swing.JToggleButton SAVE_BTTN;
    // End of variables declaration                   
}
