/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapid_rentals;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;


import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class CustomerNewBooking extends javax.swing.JFrame {

    /**
     * Creates new form CustomerNewBooking
     */
    public CustomerNewBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        s = new javax.swing.JLabel();
        BookingName_lbl = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        StartDate_lbl = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        EndDate_lbl = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        CarName_lbl = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        kmTravelled_lbl = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        EstimatedBill_lbl = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        ShowBill_bttn = new javax.swing.JToggleButton();
        Done_bttn = new javax.swing.JToggleButton();
        GoBack_bttn = new javax.swing.JToggleButton();
        LogOut_bttn = new javax.swing.JToggleButton();
        Rate_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        setPreferredSize(new java.awt.Dimension(428, 350));
        getContentPane().setLayout(null);

        BookingName_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BookingName_lbl.setText("BOOKING NAME");
        getContentPane().add(BookingName_lbl);
        BookingName_lbl.setBounds(71, 0, 105, 28);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(207, 0, 108, 28);

        StartDate_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        StartDate_lbl.setText("START DATE");
        getContentPane().add(StartDate_lbl);
        StartDate_lbl.setBounds(71, 39, 105, 27);
        getContentPane().add(tf2);
        tf2.setBounds(207, 39, 108, 27);

        EndDate_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EndDate_lbl.setText("END DATE");
        getContentPane().add(EndDate_lbl);
        EndDate_lbl.setBounds(71, 72, 105, 29);
        getContentPane().add(tf3);
        tf3.setBounds(207, 72, 108, 29);

        CarName_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CarName_lbl.setText("CAR NAME");
        getContentPane().add(CarName_lbl);
        CarName_lbl.setBounds(71, 112, 105, 28);

        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf4);
        tf4.setBounds(207, 112, 108, 28);

        kmTravelled_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kmTravelled_lbl.setText("km  TRAVELLED ");
        getContentPane().add(kmTravelled_lbl);
        kmTravelled_lbl.setBounds(71, 146, 105, 23);

        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        getContentPane().add(tf5);
        tf5.setBounds(207, 146, 108, 28);

        EstimatedBill_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EstimatedBill_lbl.setText("ESTIMATED BILL");
        getContentPane().add(EstimatedBill_lbl);
        EstimatedBill_lbl.setBounds(18, 209, 105, 28);

        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        getContentPane().add(tf6);
        tf6.setBounds(141, 209, 105, 24);

        ShowBill_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ShowBill_bttn.setText("SHOW BILL");
        ShowBill_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBill_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(ShowBill_bttn);
        ShowBill_bttn.setBounds(276, 209, 110, 30);

        Done_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Done_bttn.setText("DONE");
        Done_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Done_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(Done_bttn);
        Done_bttn.setBounds(141, 255, 105, 23);

        GoBack_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GoBack_bttn.setText("GO BACK");
        GoBack_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBack_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(GoBack_bttn);
        GoBack_bttn.setBounds(0, 270, 105, 23);

        LogOut_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LogOut_bttn.setText("LOG OUT");
        LogOut_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut_bttn);
        LogOut_bttn.setBounds(290, 270, 105, 23);

        Rate_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Rate_lbl.setText("          Rate -15 Rupees per km");
        getContentPane().add(Rate_lbl);
        Rate_lbl.setBounds(88, 185, 312, 13);

        pack();
    }// </editor-fold>                        

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void GoBack_bttnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        CustomerShow_BookCar ob=new CustomerShow_BookCar();
        ob.setVisible(true);
    }                                           

    private void LogOut_bttnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        Customer_Login o=new Customer_Login();
        o.setVisible(true);
    }                                           

    private void ShowBill_bttnActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        double a=Double.parseDouble(tf5.getText());
        double nt=15*a;
        tf6.setText(""+nt);
        
        
    }                                             

    private void Done_bttnActionPerformed(java.awt.event.ActionEvent evt) {                                          
 String url = "jdbc:mysql://localhost:3306/login";
        String user = "root";
        String password = "01234";
 
        String a=tf1.getText();
        String b=tf2.getText();
        String c=tf3.getText();
        String d=tf4.getText();
        String e=tf5.getText();
       double r=Double.parseDouble(e);
        double nt=15*r;
        
        
                 
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            String sql="insert into booking_info(Booking_Name,Start_Date,End_Date,Car_name,Bill_amount,km_Travelled)" + "values (?,?,?,?,?,?)";
            
            PreparedStatement statement = conn.prepareStatement(sql);
 
              statement.setString(1, a);
              statement.setString(2, b);
              statement.setString(3, c);
              statement.setString(4, d);
              statement.setString(5, e);
              statement.setDouble(6, nt);
              
 
            int row = statement.executeUpdate();
            if (row > 0) {
                JOptionPane.showMessageDialog(null,"Booking Done");
            }
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }       
    }                                         

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
       
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerNewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerNewBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BookingName_lbl;
    private javax.swing.JLabel CarName_lbl;
    private javax.swing.JToggleButton Done_bttn;
    private javax.swing.JLabel EndDate_lbl;
    private javax.swing.JLabel EstimatedBill_lbl;
    private javax.swing.JToggleButton GoBack_bttn;
    private javax.swing.JToggleButton LogOut_bttn;
    private javax.swing.JLabel Rate_lbl;
    private javax.swing.JToggleButton ShowBill_bttn;
    private javax.swing.JLabel StartDate_lbl;
    private javax.swing.JLabel kmTravelled_lbl;
    private javax.swing.JLabel s;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    // End of variables declaration                   


}
