/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
package rapid_rentals;

import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class CustomerShow extends javax.swing.JFrame {

    /**
     * Creates new form CustomerShow
     */
    
    public CustomerShow() {
        initComponents();
        DisplayTable();
    }
    
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Goback_bttn = new javax.swing.JToggleButton();
        Logout_bttn = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        setPreferredSize(new java.awt.Dimension(428, 350));
        getContentPane().setLayout(null);

        Goback_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Goback_bttn.setText("GO BACK");
        Goback_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Goback_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(Goback_bttn);
        Goback_bttn.setBounds(10, 257, 105, 23);

        Logout_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Logout_bttn.setText("LOG OUT");
        Logout_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(Logout_bttn);
        Logout_bttn.setBounds(285, 257, 105, 23);

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(tab1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 30, 380, 130);

        pack();
    }// </editor-fold>                        

    private void Logout_bttnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        Customer_Login o=new Customer_Login();
        o.setVisible(true);
    }                                           

    private void Goback_bttnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        CustomerShow_BookCar o=new CustomerShow_BookCar();
        o.setVisible(true);
    }                                           
private void DisplayTable()      
{
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        try{
          // Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","01234");
           String loginTable="select * from car_info" ;
           PreparedStatement psmt=conn.prepareStatement(loginTable);
           ResultSet rs=psmt.executeQuery();
           tab1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "created not");
        }
}
    /**
     * @param args the command line arguments
     */
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
           //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerShow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton Goback_bttn;
    private javax.swing.JToggleButton Logout_bttn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tab1;
    // End of variables declaration                   

}
