/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class CustomerShow_BookCar extends javax.swing.JFrame {

    /**
     * Creates new form CustomerShow_BookCar
     */
    public CustomerShow_BookCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LOG_OUT_jToggleButton1 = new javax.swing.JToggleButton();
        Show_bttn = new javax.swing.JToggleButton();
        New_bttn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        getContentPane().setLayout(null);

        LOG_OUT_jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LOG_OUT_jToggleButton1.setText("LOG OUT");
        getContentPane().add(LOG_OUT_jToggleButton1);
        LOG_OUT_jToggleButton1.setBounds(283, 245, 104, 32);

        Show_bttn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Show_bttn.setText("SHOW CARS");
        getContentPane().add(Show_bttn);
        Show_bttn.setBounds(140, 50, 130, 40);

        New_bttn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        New_bttn.setText("NEW BOOKING");
        getContentPane().add(New_bttn);
        New_bttn.setBounds(140, 120, 130, 40);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerShow_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerShow_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerShow_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerShow_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerShow_BookCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton LOG_OUT_jToggleButton1;
    private javax.swing.JToggleButton New_bttn;
    private javax.swing.JToggleButton Show_bttn;
    // End of variables declaration                   
}
