/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Customer_Signup extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Signup
     */
    public Customer_Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        NAME_jLabel1 = new javax.swing.JLabel();
        NAME_jTextField1 = new javax.swing.JTextField();
        PASSWORD_jLabel2 = new javax.swing.JLabel();
        PASSWORD_jTextField2 = new javax.swing.JTextField();
        SAVE_jToggleButton1 = new javax.swing.JToggleButton();
        GO_BACK_jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        getContentPane().setLayout(null);

        NAME_jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NAME_jLabel1.setText("         NAME");
        getContentPane().add(NAME_jLabel1);
        NAME_jLabel1.setBounds(90, 60, 80, 50);

        NAME_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME_jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(NAME_jTextField1);
        NAME_jTextField1.setBounds(180, 70, 120, 30);

        PASSWORD_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PASSWORD_jLabel2.setText("PASSWORD");
        getContentPane().add(PASSWORD_jLabel2);
        PASSWORD_jLabel2.setBounds(90, 120, 70, 40);

        PASSWORD_jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORD_jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(PASSWORD_jTextField2);
        PASSWORD_jTextField2.setBounds(180, 120, 120, 30);

        SAVE_jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SAVE_jToggleButton1.setText("SAVE");
        SAVE_jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVE_jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE_jToggleButton1);
        SAVE_jToggleButton1.setBounds(133, 179, 100, 30);

        GO_BACK_jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GO_BACK_jToggleButton2.setText("GO BACK");
        GO_BACK_jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GO_BACK_jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(GO_BACK_jToggleButton2);
        GO_BACK_jToggleButton2.setBounds(10, 253, 100, 30);

        pack();
    }// </editor-fold>                        

    private void PASSWORD_jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void NAME_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void SAVE_jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void GO_BACK_jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton GO_BACK_jToggleButton2;
    private javax.swing.JLabel NAME_jLabel1;
    private javax.swing.JTextField NAME_jTextField1;
    private javax.swing.JLabel PASSWORD_jLabel2;
    private javax.swing.JTextField PASSWORD_jTextField2;
    private javax.swing.JToggleButton SAVE_jToggleButton1;
    // End of variables declaration                   
}
