/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
package rapid_rentals;
public class CustomerShow extends javax.swing.JFrame {

    /**
     * Creates new form CustomerShow
     */
    
    public CustomerShow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Show_table = new javax.swing.JTable();
        Goback_bttn = new javax.swing.JToggleButton();
        Logout_bttn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapid Rentals");
        setPreferredSize(new java.awt.Dimension(428, 350));
        getContentPane().setLayout(null);

        Show_table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Show_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Name", "Capacity", "Brand", "Engine", "Fuel", "Model"
            }
        ));
        jScrollPane1.setViewportView(Show_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 76, 390, 120);

        Goback_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Goback_bttn.setText("GO BACK");
        getContentPane().add(Goback_bttn);
        Goback_bttn.setBounds(10, 257, 105, 23);

        Logout_bttn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Logout_bttn.setText("LOG OUT");
        getContentPane().add(Logout_bttn);
        Logout_bttn.setBounds(285, 257, 105, 23);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerShow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton Goback_bttn;
    private javax.swing.JToggleButton Logout_bttn;
    private javax.swing.JTable Show_table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
